### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by dev-nekko**
Thanks for the review and sorry for the mistakes

### CODE REVIEW

**Comment by sanjus-robotic-studio** [comment]
It is okay, Everyone makes mistakes but we should correct it. 

Happy Coding :)

**Comment by sanjus-robotic-studio** [comment]
Hi, 
   your Profile image is missing could you add it and create a new pull request.

**Comment by dev-nekko** [comment]
Hi my profile image was there or i need to add another image and delete the one before?

**Comment by sanjus-robotic-studio** [comment]
As your first PR was reverted you just need to upload the image and create a pull request

**Comment by dev-nekko** [comment]
Yes i see it now and send a new PR thanks for the observations

**Pull request merged**
